name: deploy maven package
on: 
  push:
    paths: 
      - '.github/workflows/mavendeploy.yml'
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven 
      run: mvn -B clean verify 
      #eee
    - name: deploy package
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/zhuorg -Dtoken=$PackagePAT
      env:
        USERNAME: ${{github.actor}}
        PackagePAT: ${{secrets.PublishPG}}
