name: deploy maven package
on: push
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: mvn deploy --settings settings.xml
      env: 
        Token: ${{secrets.PackagePAT}}
        PackagePAT: ${{secrets.PackagePAT}}
