name: deploy maven package
on: push
jobs: 
  job1:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    # --settings settings.xml
    - run: mvn deploy --settings settings.xml
      env: 
        PackagePAT: ${{secrets.PackagePAT}}
        USENAME: ${{ github.actor }}
